### DISCUSSION TITLE
Tutorial on building patterns and block styles with Details/Summary block

### DISCUSSION THREAD

**Discussion by justintadlock** [WordPress/developer-blog-content#104] [Topic Ideas]
The [Details/Summary block](https://github.com/WordPress/gutenberg/pull/45055) is still experimental, but I wanted to start playing around with some ideas on what this block could be used for and whether it's worth exploring as tutorial content.

The block would offer a browser-native way to build out features like an accordion (no JS needed). I could see this working well as a "create a pattern" tutorial and potentially even some use cases for custom block style variations or a combination of both.

Here's a really quick preview of using Details/Summary to build out an accordion (**Edit:** note that an "accordion" might not be the best option for a11y---needs research---just an example exploration):

[details-summary-accordion.webm](https://user-images.githubusercontent.com/1816309/234683178-50a2d923-4a2f-4485-903f-b4185a2983c4.webm)

**Comment by justintadlock** [comment]
Alternate PR with a different take on the block: https://github.com/WordPress/gutenberg/pull/49808

**Comment by justintadlock** [comment]
Idea for using for code blocks:

![image](https://user-images.githubusercontent.com/1816309/235177916-e643420d-9fa4-4ead-8986-87db370159f9.png)

**Comment by justintadlock** [comment]
Idea for a FAQs pattern:

![image](https://user-images.githubusercontent.com/1816309/235928886-20048313-ff08-44a6-9da3-bf5caad1090c.png)

**Comment by justintadlock** [comment]
Spoiler style:

![image](https://user-images.githubusercontent.com/1816309/235935131-a4e572c8-8b9c-4aa9-81a8-12bf3432a52d.png)

CSS code (note this may need to be updated):

```css
.wp-block-details.is-style-spoiler {
	border-left: 5px solid #fcb900b8;
}

.wp-block-details.is-style-spoiler summary {
	padding: 1rem;
	font-weight: bold;
	background: #fcb90029;
}

.wp-block-details.is-style-spoiler summary::marker {
	content: "⚠️ "
}

.wp-block-details.is-style-spoiler .wp-block-details-content {
	padding-left: 1rem;
}
```
