### DISCUSSION TITLE
When Block Styles Are Not Enough: Extending Blocks in Themes

### DISCUSSION THREAD

**Discussion by justintadlock** [WordPress/developer-blog-content#130] [Topic Ideas]
**Tutorial proposal:**

One of the oft-repeated issues with WordPress' block styles system is that users can only add one style to a block at a time. More on this Gutenberg ticket: https://github.com/WordPress/gutenberg/issues/14598

There are pros and cons to this system:

- **Pro:** It keeps highly distinctive styles from clashing.
- **Con:** You can't mix and match simpler or smaller design pieces that wouldn't clash.

_There has to be a middle ground..._

## How to combine block styles?

That is the question that has frustrated many developers. For example, suppose you had a "Large Text" style and a separate "Gradient Outline" style for the block. Do you create a third style named "Large Text with Gradient Outline"? That is what some devs have resorted to, but it is a slippery slope with each new style you add. And, you would never do this in a solid design system.

At the end of the day, a block style is nothing more than a simple class that uses a standard `.is-style-{$slug}` naming scheme. The reason this is great for themes is that it doesn't negatively impact user content if/when users switch themes.

And this is (relatively) simple to recreate. 

On the most low-effort DX end of the scale, you just have users input custom classes into the "Additional CSS Class(es)" box and call it a day. But, that makes for a poor UX.

On the other end of the spectrum, you build custom controls and let the user interact with them through the interface. Unlike custom blocks or plugins that add custom attributes, this system would use CSS classes under the hood. That means it also plays nicely with the WordPress theme review guidelines.

I've created several solutions in the past couple of weeks for testing this system. It works really, really well.

For example, here's a "Gradient Outline" picker that I put together:

![image](https://github.com/WordPress/developer-blog-content/assets/1816309/b27982ac-355c-4a87-839d-83fc6abac438)

## Teaching theme authors block editor JavaScript

There are two things at play:

1. Theme authors must first learn how to set up the `@wordpress/scripts` package and integrate it into a theme. AFAIK, there is no documentation aimed directly at theme dev, but it definitely works.
2. Introduce theme authors to concepts that would typically fall under "block" development.

This is potentially a two-part series because both of the topics could be relatively beefy on their own.

**Comment by justintadlock** [comment]
**Sharing some other custom alternatives to block styles:**

## Text shadows

This one is probably the simplest, so it'd make for a good introduction to the concept in the post:

![image](https://github.com/WordPress/developer-blog-content/assets/1816309/3390466a-2795-4478-9030-43150ca964a3)

## List markers/bullets

This one is almost as simple as the text-shadow, but it has an extra hurdle to jump when dealing with `<ul>` vs. `<ol>`:

![image](https://github.com/WordPress/developer-blog-content/assets/1816309/4bf6fe6c-0d56-483e-b634-895ac444232f)

## Color variations (color groups) for style entire sections

This is probably too complex for an introductory tutorial because it would need to discuss color design systems in detail:

![image](https://github.com/WordPress/developer-blog-content/assets/1816309/8ba102b3-1e08-4baa-8c10-5f4afa5a8c8e)

**Comment by marybaum** [comment]
You've got my vote! I'm dealing with all these and more on a site I'm building — well, actually, I'm doing without.

**Comment by justintadlock** [comment]
I was trying to think of a use case that would show off what you could do while also being a bit fun. Since I had no electricity for the day, a full laptop battery charge, and nothing but my imagination to keep me company, I present to you an **emoji-_fied_ Separator block**. Right now, this just uses the regular block styles system, but you can see how easily that gets out of hand. This should be also be a simple enough example to keep this tutorial within a reasonable length.

The big things would be:

- Creating a custom control for the icon/emoji selection via a block filter.
- Pairing each emoji with a core background-color/gradient and setting this dynamically (can probably pair these with theme-defined gradients too). Haven't tried this yet, so I'm hoping this isn't any tougher than using `setAttributes` from within the filter.
- Removing the block style class (if the user adds one since this wouldn't pair well with other styles). I'm actually not sure of the best way to do this just yet.

https://github.com/WordPress/developer-blog-content/assets/1816309/acb3bdbf-4857-4b2a-b5ed-59b96d183c4e

**Backup of SCSS for safekeeping:**

```scss
// Icon styles.
hr.wp-block-separator[class*=is-style-icon] {
	display: flex;
	justify-content: center;
	border: none;
	text-align: center;

	// Some characters get cut off. This ensures they are visible.
	overflow: visible;

	// Use `!important` to overrule core's use of the `background` shorthand
	// instead of the targeted property itself.
	background-color: transparent !important;
	background-repeat: repeat-x !important;
	background-position: 0% 50% !important;
	background-size: 100% 2px !important;

	// Don't use `!important` for the background image, which allows
	// background gradients to work.
	background-image: var( --hr-bg, linear-gradient( 90deg, currentColor, currentColor ) );

	// If there's a background color, use our custom gradient which uses the
	// current color.
	&:where( [class*=-background-color] ) {
		background-image: linear-gradient( 90deg, currentColor, currentColor );
	}

	&::before {
		content: var( --hr-icon, "\2766" ); // floral heart default.
		padding: 0 0.25em;
		font-size: var( --wp--preset--font-size--xl );
		line-height: 1;
		background-color: var( --color-base, var( --wp--preset--color--base ) );
	}
}

.is-style-icon-♫ { --hr-icon: "♫"; } // beamed eighth notes
.is-style-icon-★ { --hr-icon: "★"; } // black star
.is-style-icon-❦ { --hr-icon: "❦"; } // floral heart
.is-style-icon-☘ { --hr-icon: "☘"; } // shamrock
.is-style-icon-✻ { --hr-icon: "✻"; } // teardrop spoked asterisk

// We can set these backgrounds dynamically if moving to a custom control and 
// outside of the block styles system.
.is-style-icon-☀️  { --hr-icon: "☀️";  --hr-bg: var( --wp--preset--gradient--true-sunset ); }
.is-style-icon-🪶 { --hr-icon: "🪶";  --hr-bg: var( --wp--preset--gradient--shy-rainbow ); }
.is-style-icon-🍃 { --hr-icon: "🍃"; --hr-bg: var( --wp--preset--gradient--emerald ); }
.is-style-icon-✏️  { --hr-icon: "✏️"; --hr-bg: var( --wp--preset--gradient--mohave ); }
.is-style-icon-🌻 { --hr-icon: "🌻"; --hr-bg: var( --wp--preset--gradient--true-sunset ); }
.is-style-icon-⛱️ { --hr-icon: "⛱️"; --hr-bg: var( --wp--preset--gradient--powerpuff ); }
```
